name: config-snap
base: core18
version: '0.1'
summary: Configure some defaults on Ubuntu Core images
description: |
  This little helper snap creates an ubuntu user and copies a netplan.yaml
  in place on a freshly booted Ubuntu core image.

  You need to connect the network-setup-control and account-control interfaces
  from a gadget.yaml config line to make this work.

grade: stable
confinement: strict

plugs:
  account-control:
  network-setup-control:

parts:
  netplanyaml:
    source: default-netplan-config
    plugin: nil
    override-build: |
      cp netplan.yaml $SNAPCRAFT_PART_INSTALL/
